name: Compile Examples

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Arduino CLI
        working-directory: ./
        run: |
          mkdir -vp ~/.local/bin
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh |
            BINDIR=~/.local/bin sh
          arduino-cli core install arduino:avr

      - name: Compile Examples
        working-directory: ./
        run: |
          git submodule update --init --recursive
          make compile
