name: Test Library

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Clang++, Make and CMake
        run: |
          sudo apt update
          sudo apt install -y clang make cmake

      - name: Build the C++ Dependencies
        working-directory: ./
        run: |
          make deps/gtest

      - name: Run All Tests
        working-directory: ./
        run: |
          make test
